apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-her-thing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-her-thing
  template:
    metadata:
      labels:
        app: code-her-thing
    spec:
      containers:
        - name: code-her-thing
          image: CONTAINER_IMAGE
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: code-her-thing
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: code-her-thing
