apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackathon-app
  template:
    metadata:
      labels:
        app: hackathon-app
    spec:
      containers:
        - name: hackathon-app
          image: CONTAINER_IMAGE
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: hackathon-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: hackathon-app
