apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeHerThing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codeHerThing
  template:
    metadata:
      labels:
        app: codeHerThing
    spec:
      containers:
        - name: codeHerThing
          image: CONTAINER_IMAGE
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: codeHerThing
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: codeHerThing
