apiVersion: v1
kind: Service
metadata:
  name: code-her-thing
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: code-her-thing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-her-thing
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: code-her-thing
  template:
    metadata:
      labels:
        app: code-her-thing
    spec:
      containers:
        - name: code-her-thing
          image: CONTAINER_IMAGE
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 80
